### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by dgruntz** [explore-it-org/robby-app#23]
The warnings which appear on startup should be eliminated by replacing the deprecated classes by the new ones.

![image](https://user-images.githubusercontent.com/1516800/57132644-8419f780-6da0-11e9-8506-325b5b1ae40f.png)

Jürg already did that for his terminal app, so either look there or ask him.

**Comment by MichaelStotzer** [comment]
ListView:
We are using the component SinglePickerMaterialDialog from the project https://github.com/hectahertz/react-native-material-dialog. There exists a pull request (#48) to replace ListView by FlatList, but this has been open since october 2018, so I don't expect the pull request to be merged into master anymore. Maybe simply adapt those changes?
ViewPagerAndroid:
This warning doesn't occur anymore on both android and ios devices.

ios warning:
![image](https://user-images.githubusercontent.com/49184931/59343397-0edd0300-8d0c-11e9-9a55-b4039ffd3977.png)
